# ~~ Generated by projen. To modify, edit .projenrc.py and run "npx projen".

import json
from setuptools import setup

kwargs = json.loads(
    """
{
    "name": "qnddb",
    "python_requires": ">=3.7",
    "author": "Rico Hermans",
    "author_email": "rix0rrr@gmail.com",
    "version": "0.1.0"
}
"""
)

setup(**kwargs)
